# Testing Dockerfile

FROM debian:stable-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    dbus-x11 \
    dconf-cli \
    fluxbox \
    python3-cairo \
    rhythmbox \
    rhythmbox-plugins \
    tigervnc-standalone-server \
    tigervnc-common \
    xterm
RUN mkdir /root/.vnc && echo foobar | vncpasswd -f > /root/.vnc/passwd && chmod 0600 /root/.vnc/passwd
CMD /root/.local/share/rhythmbox/plugins/rhythmbox-tray-icon/test.sh